name: "GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "test/gh-pages"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - name: "Run pip install"
        run: >
          python3 -m pip install -r requirements.txt
      - name: "Run MkDocs(build)"
        run: >
          python3 -m mkdocs build --site-dir _site

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'
      - uses: actions/deploy-pages@v2
